### ISSUE TITLE
NameError: name 'PretrainedConfig' is not defined

### ISSUE THREAD

**Issue by Immortality-IMT** [LumenScopeAI/BrainTransformers-SNN-LLM#1]
python3 run.py
Traceback (most recent call last):
  File "/home/x/BrainTransformers-SNN-LLM/transformers/utils/import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/x/BrainTransformers-SNN-LLM/transformers/models/braingpt/modeling_braingpt.py", line 25, in <module>
    from .configuration_braingpt import BrainGPTConfig
  File "/home/x/BrainTransformers-SNN-LLM/transformers/models/braingpt/configuration_braingpt.py", line 1, in <module>
    class BrainGPTConfig(PretrainedConfig):
NameError: name 'PretrainedConfig' is not defined

I copy and paste the custom transformer package into site packages or virtual environment. 

Running python3 run.py produces this error

**Comment by Immortality-IMT** [comment]
Custom transfomer that comes with git clone: BrainTransformers-SNN-LLM/transformers/models/braingpt/configuration_braingpt.py

from transformers import PretrainedConfig
